services:
  - type: web
    name: carvex-carparts
    env: php
    plan: free
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-damp-queen-ahu1j223.c-3.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
